version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: webpack
    versions:
    - 5.34.0
