service:
  name: poc-sls-typescript

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_REGION,"us-west-1"}
  endpointType: REGIONAL
  memorySize: 512
  reserveConcurrency: 10
  timeout: 10
  logRetentionInDays: 14
  deploymentBucket:
    name: ${ssm:/${self:provider.stage}/deploymentBucket}
    serverSideEncryption: AES256
  versionFunctions: false  
  apiGateway:
    minimumCompressionSize: 1024
    description: API Test Typescript
  tracing:
    lambda: true
    apiGateway: true
  logs:
    restApi: true

package:
  individually: true    

plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-optimize

custom:     
  customDomain:
    domainName: ${ssm:/${self:provider.stage}/domain}
    basePath: typeahead
    endpointType: regional
    createRoute53Record: false  
  dotenv:    
    include:
      - AWS_XRAY_CONTEXT_MISSING  

functions:
  getExample:
    handler: src/handler.getExample
    events:
      - http:
          method: get
          path: example
          cors: true
  postExample:
    handler: src/handler.postExample
    events:
      - http:
          method: post
          path: example
          cors: true
          request:
           schema:
              application/json: ${file(module/createExample.json)}
