version: 2

defaults: &defaults  
  docker:
    - image: circleci/node:lts 

jobs:
  build:
    <<: *defaults
    steps:
      - checkout      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: 
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: List dir
          command: pwd && ls -lh
      - store_artifacts:
          path: coverage
          prefix: coverage
      - save_cache:   
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - node_modules
            - coverage  
  upload_report:
    <<: *defaults    
    steps:      
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name:  Upload coverage
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            ./tmp/cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
            ./tmp/cc-test-reporter upload-coverage         


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - upload_report:
          requires:
            - build
          filters:
            branches:
              only: master