name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm test
          echo ${{ matrix.node-version }} ${{ github.ref }}
        env:
          CI: true
      - name: Upload coverage
        #if: github.ref == 'refs/heads/master'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
          ./tmp/cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
          ./tmp/cc-test-reporter upload-coverage
          echo $CC_TEST_REPORT_ID
